import Head from "next/head";
import Image from "next/image";
import homeStyles from "../styles/Home.module.css";
import headerStyles from "../styles/Header.module.css";
import { BiMailSend } from "react-icons/bi";

export default function Home() {
  return (
    <div className={homeStyles.pageContainer}>
      <Head>
        <title>Tony Migeon Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={headerStyles.header}>
        <div className={headerStyles.headerContainer}>
          <img
            className={headerStyles.logo}
            alt="logo.png"
            src="/logo.png"
          ></img>
          <span className={headerStyles.contactText}>
            Contact
            <BiMailSend className = {headerStyles.contactLogo} size={25}/>
          </span>
        </div>
      </header>
      <main>
        <div></div>
      </main>
    </div>
  );
}
