import Head from "next/head";
import { useRouter } from "next/router";
import homeStyles from "../styles/Home.module.css";
import Header from "../components/Header";
import Link from "next/link";
import {
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiMaterialui,
  SiChakraui,
  SiSass,
} from "react-icons/si";
import { BiMailSend, BiFolderOpen, BiUserPin } from "react-icons/bi";

const Content = {
  en: {
    jobText: "Front End developper",
    jobDescText: "Open to Remote Jobs Offers.",
    jobDescText2: "Job opportunities.",
    button1: "Projects",
    button2: "About Me",
  },
  fr: {
    jobText: "Développeur Front End",
    jobDescText: "Ouvert aux offres en télétravail.",
    jobDescText2: "d'opportunités d'emplois.",
    button1: "Projets",
    button2: "Profil",
  },
};

export default function Home() {
  const router = useRouter();
  const { locale, locales, defaultLocale, asPath } = useRouter();
  const { jobText, jobDescText, jobDescText2, button1, button2 } =
    Content[locale];
  const advancedSkills = {
    skills: [
      { name: "TypeScript", icon: <SiTypescript size={30} /> },
      { name: "Javascript", icon: <SiJavascript size={30} /> },
      { name: "HTML5", icon: <SiHtml5 size={30} /> },
      { name: "CSS3", icon: <SiCss3 size={30} /> },
      { name: "Sass", icon: <SiSass size={30} /> },
      { name: "Chakra-UI", icon: <SiChakraui size={30} /> },
    ],
  };

  const handleClick = (e) => {
    e.preventDefault();
    router.push("/projects");
  };

  return (
    <div className={homeStyles.pageContainer}>
      <Head>
        <title>Tony Migeon Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main>
        <div className={homeStyles.mainContainer}>
          <h1 className={homeStyles.nameText}>Tony Migeon</h1>
          <h3 className={homeStyles.jobText}>{jobText}</h3>
          <h2 className={homeStyles.reactJobText}>React</h2>
          <div className={homeStyles.jobDescTextContainer}>
            <p className={homeStyles.jobDescText}>{jobDescText}</p>
            {/* <p className={homeStyles.jobDescText}>{jobDescText2}</p> */}
            <button className={homeStyles.button} onClick={handleClick}>
              {/* <BiFolderOpen className={homeStyles.contactLogo} size={35} /> */}
              <span className={homeStyles.buttonSpan}>{button1}</span>
            </button>
          </div>
          <div className={homeStyles.skills}>
            {advancedSkills.skills.map((skill, index) => {
              return (
                <div key={index} className={homeStyles.singleSkillContainer}>
                  <h4 className={homeStyles.advancedSkills}>{skill.name}</h4>
                  {skill.icon}
                </div>
              );
            })}
          </div>
          <div className={homeStyles.buttonContainer}>
            {/* <span className={homeStyles.contactText}>
              Contact
              
            </span> */}
            <button className={homeStyles.button} onClick={handleClick}>
              {/* <BiMailSend className={homeStyles.contactLogo} size={30} /> */}
              <span className={homeStyles.buttonSpan}>Contact</span>
            </button>
            <button className={homeStyles.button}>
              {/* <BiUserPin className={homeStyles.contactLogo} size={30} /> */}
              <span className={homeStyles.buttonSpan}>{button2}</span>
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}
